name: Check for new nodejs versions

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Fetch new versions
        run: |
          docker run nvitaterna/nodejs-version-info:latest list --all --pretty > new.versions.json

      - name: Compare versions
        id: set-versions
        run: |
          echo "versions=$(jq -c -n '[inputs] as $files | ($files[0] - $files[1])' new.versions.json versions.json)" >> $GITHUB_OUTPUT

      - name: Check if new versions exist and set output
        id: check-versions
        run: |
          if [[ "${{ steps.set-versions.outputs.versions }}" == "" || "${{ steps.set-versions.outputs.versions }}" == "[]" ]]; then
            echo "No new versions found."
            echo "new_versions=false" >> $GITHUB_OUTPUT
          else
            echo "New versions found."
            echo "new_versions=true" >> $GITHUB_OUTPUT
          fi

      - name: Map versions output to comma-separated string
        if: steps.check-versions.outputs.new_versions == 'true'
        id: set-versions-string
        run: |
          echo "versions=$(jq -r '. | map(.version) | join(", ")' <<< '${{ steps.set-versions.outputs.versions }}')" >> $GITHUB_OUTPUT

      - name: Overwrite versions.json with new.versions.json
        if: steps.check-versions.outputs.new_versions == 'true'
        run: |
          mv new.versions.json versions.json

      - name: Create PR
        if: steps.check-versions.outputs.new_versions == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: |
            chore(node): add new version(s)
            versions: ${{ steps.set-versions-string.outputs.versions }}
          title: "chore(node): add new version(s)"
          body: |
            New version(s) added: ${{ steps.set-versions-string.outputs.versions }}

            Auto-generated by [create-pull-request][1] and [nodejs-version-info][2].

            [1]: https://github.com/peter-evans/create-pull-request

            [2]: https://github.com/nvitaterna/nodejs-version-info
          branch: "update-versions"
          delete-branch: true
          base: "main"
