name: Check for new nodejs versions

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch new versions
        run: |
          docker run nvitaterna/nodejs-version-info:latest list --all --pretty > new.versions.json

      - name: Compare versions
        id: set-versions
        run: |
          echo "versions=$(jq -c -n '[inputs] as $files | ($files[0] - $files[1]) | map({ version: .version, tags: [(to_entries | map(select(.value == true) | .key))[], .version] })' new.versions.json versions.json)" >> $GITHUB_OUTPUT

      - name: Check if new versions exist
        run: |
          if [[ "${{ steps.set-versions.outputs.versions }}" == "" || "${{ steps.set-versions.outputs.versions }}" == "[]" ]]; then
            echo "No new versions found."
            exit 0
          else
            echo "New versions found."
          fi

      - name: Map versions output to comma-separated string
        id: set-versions-string
        run: |
          echo "versions=$(jq -r '. | map(.version) | join(", ")' <<< '${{ steps.set-versions.outputs.versions }}')" >> $GITHUB_OUTPUT

      - name: Overwrite verisions.json with new.versions.json
        run: |
          mv new.versions.json versions.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: |
            chore(node): add new version(s)
            versions: ${{ steps.set-versions-string.outputs.versions }}
          title: "chore(node): add new version(s)"
          body: |
            New version(s) added: ${{ steps.set-versions-string.outputs.versions }}

            Auto-generated by [create-pull-request][1] and [nodejs-version-info][2].

            [1]: https://github.com/peter-evans/create-pull-request

            [2]: https://github.com/nvitaterna/nodejs-version-info
          branch: "update-versions"
          delete-branch: true
          base: "main"
